### ISSUE TITLE
Why shouldn't I use painless?

### ISSUE THREAD

**Issue by AriaFallah** [taylorhakes/painless#12]
I like painless and I've already been testing a bit with it; however, I would like to know your objective opinion on why I shouldn't use painless.

You could say things say as a weak ecosystem, but that's already pretty obvious.

When does painless fall short compared to its competitors?

**Comment by af** [comment]
Things I can think of:

* You need tests to run in the browser (like Mocha). Not sure how easy/possible this is with painless
* You need isolated parallel tests (like AVA). See #8 
* You don't like chai assertions, or you prefer its non-`assert` flavours
* Ecosystem, as you mentioned
* Project is still young and docs aren't fleshed out yet (it's still really easy to figure out though)

Obviously none of those are critical for me, otherwise I wouldn't be watching this repo. But I can see why each of them would be important to others.

**Comment by taylorhakes** [comment]
I think @af gave a good list. 
I would add that some libraries have integrated coverage, but I don't necessarily think that is a big deal. I am still undecided if that is necessary. It is really easy to use [istanbul](https://github.com/gotwarlost/istanbul) or [nyc](https://github.com/bcoe/nyc) with painless.

I compared the pros and cons in the readme, https://github.com/taylorhakes/painless#compared-to-other-libraries- . If you see other benefits to other libraries, please let me know. I want to make sure to list a fair comparison.

**Comment by af** [comment]
Personally, I don't see the point in integrated coverage, when istanbul works really well and is quite simple to use already.

**Comment by taylorhakes** [comment]
I agree. Mocha and node-tap have done it, so I just wanted to put it out there.

**Comment by taylorhakes** [comment]
@AriaFallah Thanks for the question. I am going close this issue. If you need any more information, please comment.
